[project]
name = "hns"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord>=2.3.2",
    "python-dotenv>=1.1.1",
    "regex>=2025.7.31",
    "tabulate>=0.9.0",
]
